# Generated by Django 4.2.7 on 2026-01-05 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True, verbose_name='Rok')),
                ('euro_exchange_rate', models.DecimalField(decimal_places=4, max_digits=5, verbose_name='Kurs euro')),
                ('limit_euro', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Limit euro')),
                ('limit_netto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Limit zamówień netto')),
            ],
            options={
                'verbose_name': 'Limit zamówień',
                'verbose_name_plural': 'Limit zamówień',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='Typecpv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_cpv', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'CPV',
                'verbose_name_plural': 'Słownik CPV',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_id', models.CharField(max_length=4, unique=True, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ogólna nazwa przedmiotu zamówienia w ujęciu rodzajowym')),
                ('cpv', models.ManyToManyField(related_name='Genre', to='cpvdict.typecpv', verbose_name='Kody CPV')),
            ],
            options={
                'verbose_name': 'Klasyfikacja rodzajowa',
                'verbose_name_plural': 'Klasyfikacja rodzajowa',
                'ordering': ['name_id'],
            },
        ),
    ]
