# Generated by Django 4.2.1 on 2023-09-12 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0005_remove_unit_cost_type_delete_costtype'),
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Kwota brutto [zł]')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_items', to='invoices.group', verbose_name='Grupa')),
                ('invoice_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_items', to='invoices.invoice', verbose_name='Faktura')),
                ('paragraph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_items', to='invoices.paragraph', verbose_name='Paragraf')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_items', to='invoices.section', verbose_name='Rozdział')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_items', to='units.unit', verbose_name='Jednostka')),
            ],
            options={
                'verbose_name': 'Element faktury',
                'verbose_name_plural': 'Elementy faktury',
                'ordering': ['invoice_id'],
            },
        ),
        migrations.DeleteModel(
            name='FinanceSource',
        ),
    ]
