# Generated by Django 4.2.7 on 2024-04-19 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoiceitems',
            options={'ordering': ['-creation_date'], 'verbose_name': 'Element faktury', 'verbose_name_plural': '06 - Elementy faktur'},
        ),
    ]
