# Generated by Django 4.1.7 on 2023-09-10 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Rodzaj kosztu')),
            ],
            options={
                'verbose_name': 'Rodzaj kosztów',
                'verbose_name_plural': '05 - Rodzaje kosztów',
            },
        ),
        migrations.AlterModelOptions(
            name='documenttypes',
            options={'verbose_name': 'Rodzaj dokumentu księgowego', 'verbose_name_plural': '04 - Rodzaje dokumentów księgowych'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Grupa', 'verbose_name_plural': '02 - Grupy'},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-date_receipt'], 'verbose_name': 'Faktura', 'verbose_name_plural': '06 - Faktury'},
        ),
        migrations.AlterModelOptions(
            name='paragraph',
            options={'verbose_name': 'Paragraf i pozycja', 'verbose_name_plural': '03 - Paragrafy i pozycje'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['section'], 'verbose_name': 'Rozdział', 'verbose_name_plural': '01 - Rozdziały'},
        ),
    ]
