# Generated by Django 4.2.7 on 2025-07-22 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitems',
            name='consumption',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Zużycie'),
        ),
    ]
