# Generated by Django 4.2.1 on 2023-09-12 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_invoiceitems_delete_financesource'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-date_receipt'], 'verbose_name': 'Faktura', 'verbose_name_plural': '07 - Faktury'},
        ),
        migrations.AlterModelOptions(
            name='invoiceitems',
            options={'ordering': ['invoice_id'], 'verbose_name': 'Element faktury', 'verbose_name_plural': '06 - Elementy faktury'},
        ),
        migrations.AddField(
            model_name='invoiceitems',
            name='information',
            field=models.CharField(default=1, max_length=400, verbose_name='Uwagi'),
            preserve_default=False,
        ),
    ]
