# Generated by Django 4.2.7 on 2025-07-23 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_alter_invoiceitems_consumption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitems',
            name='consumption',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Zużycie'),
        ),
    ]
