# Generated by Django 4.2.1 on 2023-09-13 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0005_remove_unit_cost_type_delete_costtype'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('invoices', '0003_alter_invoice_options_alter_invoiceitems_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoiceitems',
            options={'verbose_name': 'Element faktury', 'verbose_name_plural': '06 - Elementy faktury'},
        ),
        migrations.RemoveField(
            model_name='invoiceitems',
            name='group',
        ),
        migrations.RemoveField(
            model_name='invoiceitems',
            name='id',
        ),
        migrations.RemoveField(
            model_name='invoiceitems',
            name='information',
        ),
        migrations.RemoveField(
            model_name='invoiceitems',
            name='invoice_id',
        ),
        migrations.RemoveField(
            model_name='invoiceitems',
            name='paragraph',
        ),
        migrations.RemoveField(
            model_name='invoiceitems',
            name='section',
        ),
        migrations.RemoveField(
            model_name='invoiceitems',
            name='sum',
        ),
        migrations.RemoveField(
            model_name='invoiceitems',
            name='unit',
        ),
        migrations.CreateModel(
            name='InvoiceItemsPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Kwota brutto [zł]')),
                ('information', models.CharField(max_length=400, verbose_name='Uwagi')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoiceItemsP', to='invoices.group', verbose_name='Grupa')),
                ('invoice_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoiceItemsP', to='invoices.invoice', verbose_name='Faktura')),
                ('paragraph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoiceItemsP', to='invoices.paragraph', verbose_name='Paragraf')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoiceItemsP', to='invoices.section', verbose_name='Rozdział')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoiceItemsP', to='units.unit', verbose_name='Jednostka')),
            ],
            options={
                'ordering': ['invoice_id'],
            },
        ),
        migrations.AddField(
            model_name='invoiceitems',
            name='invoiceitemspattern_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='invoices.invoiceitemspattern'),
            preserve_default=False,
        ),
    ]
