# Generated by Django 4.1.7 on 2023-09-10 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_invoice_cost_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='cost_type',
        ),
        migrations.DeleteModel(
            name='CostType',
        ),
    ]
