# Generated by Django 4.2.1 on 2023-09-11 05:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invoices', '0004_remove_invoice_cost_type_delete_costtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='doc_types',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='invoices.documenttypes', verbose_name='Rodzaj dokumentu'),
        ),
    ]
