# Generated by Django 4.2.1 on 2023-09-13 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0005_remove_unit_cost_type_delete_costtype'),
        ('invoices', '0004_alter_invoiceitems_options_remove_invoiceitems_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='swop_id',
            field=models.ManyToManyField(related_name='section', to='units.county', verbose_name='SWOP'),
        ),
    ]
