# Generated by Django 4.2.1 on 2023-09-11 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_alter_invoice_author_alter_invoice_doc_types'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paragraph',
            options={'ordering': ['paragraph'], 'verbose_name': 'Paragraf i pozycja', 'verbose_name_plural': '03 - Paragrafy i pozycje'},
        ),
    ]
