# Generated by Django 4.2.1 on 2023-09-11 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_invoice_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20, verbose_name='Typ dokumentu')),
            ],
            options={
                'verbose_name': 'Rodzaj umowy',
                'verbose_name_plural': '05 - Rodzaje umów',
            },
        ),
    ]
