# Generated by Django 4.2.1 on 2023-09-14 06:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_invoiceitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitems',
            name='consumption',
            field=models.IntegerField(default=1, verbose_name='Zużycie'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoiceitems',
            name='counterReading',
            field=models.IntegerField(default=1, verbose_name='Stan licznika'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoiceitems',
            name='measurementSystemNumber',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Nr. licznika'),
        ),
        migrations.AddField(
            model_name='invoiceitems',
            name='period_from',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Okres od'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoiceitems',
            name='period_to',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Okres do'),
            preserve_default=False,
        ),
    ]
