# Generated by Django 4.2.1 on 2023-09-11 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0008_contracttypes'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='type_contract',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='invoices.contracttypes'),
            preserve_default=False,
        ),
    ]
