# Generated by Django 4.2.1 on 2023-09-14 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invoices', '0008_invoiceitems_consumption_invoiceitems_counterreading_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoiceitems',
            options={'ordering': ['invoice_id'], 'verbose_name': 'Element faktury', 'verbose_name_plural': '06 - Elementy faktury'},
        ),
        migrations.AlterField(
            model_name='invoice',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='type_contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='invoices.contracttypes', verbose_name='Rodzaj umowy'),
        ),
        migrations.AlterField(
            model_name='invoiceitems',
            name='information',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Uwagi'),
        ),
    ]
