# Generated by Django 4.2.1 on 2023-09-14 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0009_alter_invoiceitems_options_alter_invoice_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitems',
            name='counterReading',
            field=models.IntegerField(null=True, verbose_name='Stan licznika'),
        ),
        migrations.AlterField(
            model_name='invoiceitems',
            name='period_from',
            field=models.DateField(null=True, verbose_name='Okres od'),
        ),
        migrations.AlterField(
            model_name='invoiceitems',
            name='period_to',
            field=models.DateField(null=True, verbose_name='Okres do'),
        ),
    ]
