# Generated by Django 4.2.1 on 2023-09-14 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0011_alter_invoiceitems_consumption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitems',
            name='contract_types',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='invoices.contracttypes', verbose_name='Typ umowy'),
            preserve_default=False,
        ),
    ]
