# Generated by Django 4.2.1 on 2023-09-14 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0012_invoiceitems_contract_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitems',
            name='information',
            field=models.CharField(blank=True, default='', max_length=400, null=True, verbose_name='Uwagi'),
        ),
    ]
