# Generated by Django 4.2.1 on 2023-09-15 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0015_invoiceitems_creation_date_alter_invoice_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paragraph',
            name='slug',
            field=models.SlugField(blank=True, max_length=7, null=True, unique=True),
        ),
    ]
