# Generated by Django 4.2.1 on 2023-09-18 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0005_remove_unit_cost_type_delete_costtype'),
        ('invoices', '0016_paragraph_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='type_contract',
        ),
        migrations.AlterField(
            model_name='invoiceitems',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoices.group', verbose_name='Grupa'),
        ),
        migrations.AlterField(
            model_name='invoiceitems',
            name='invoice_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoices.invoice', verbose_name='Faktura'),
        ),
        migrations.AlterField(
            model_name='invoiceitems',
            name='paragraph',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoices.paragraph', verbose_name='Paragraf'),
        ),
        migrations.AlterField(
            model_name='invoiceitems',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoices.section', verbose_name='Rozdział'),
        ),
        migrations.AlterField(
            model_name='invoiceitems',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='units.unit', verbose_name='Jednostka'),
        ),
    ]
