# Generated by Django 4.2.1 on 2023-09-19 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0020_alter_section_swop_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitems',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoices.section', verbose_name='Rozdział'),
        ),
    ]
