# Generated by Django 4.2.1 on 2023-09-19 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0022_alter_invoiceitems_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitems',
            name='information',
            field=models.TextField(blank=True, null=True, verbose_name='Informacje'),
        ),
    ]
