# Generated by Django 4.2.1 on 2023-09-20 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0023_alter_invoiceitems_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paragraph',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nazwa'),
        ),
    ]
