# Generated by Django 4.2.1 on 2023-10-08 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0025_invoiceitems_author_invoiceitems_change_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitems',
            name='sum',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Kwota brutto [zł]'),
            preserve_default=False,
        ),
    ]
