# Generated by Django 4.2.1 on 2023-10-18 06:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0026_alter_invoiceitems_sum'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoiceitems',
            options={'ordering': ['-creation_date'], 'verbose_name': 'Element faktury', 'verbose_name_plural': '06 - Elementy faktury'},
        ),
        migrations.AlterField(
            model_name='invoiceitems',
            name='counterReading',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Stan licznika'),
        ),
        migrations.AlterField(
            model_name='invoiceitems',
            name='period_from',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Okres od'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoiceitems',
            name='period_to',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Okres do'),
            preserve_default=False,
        ),
    ]
