# Generated by Django 4.2.1 on 2023-10-31 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0029_invoiceitems_consumption_second'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitems',
            name='consumption',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Zużycie'),
        ),
        migrations.AlterField(
            model_name='invoiceitems',
            name='consumption_second',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Zużycie-2'),
        ),
    ]
