# Generated by Django 4.2.1 on 2023-11-26 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0030_alter_invoiceitems_consumption_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitems',
            name='consumption_second',
        ),
    ]
