# Generated by Django 4.1.7 on 2023-03-25 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('swop_id', models.CharField(max_length=4, unique=True, verbose_name='ID SWOP')),
                ('name', models.CharField(max_length=15, unique=True, verbose_name='Powiat')),
                ('id_order', models.IntegerField(null=True, unique=True, verbose_name='Kolejność')),
            ],
            options={
                'verbose_name': 'Powiat',
                'verbose_name_plural': 'J.01 - Powiaty',
                'ordering': ['id_order'],
            },
        ),
    ]
