# Generated by Django 4.2.7 on 2024-05-15 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('swop_id', models.CharField(max_length=4, verbose_name='ID SWOP')),
                ('name', models.CharField(max_length=15, unique=True, verbose_name='Jednostka')),
                ('id_order', models.IntegerField(null=True, unique=True, verbose_name='Kolejność')),
            ],
            options={
                'verbose_name': 'Jednostka SWOP',
                'verbose_name_plural': '01 - Jednostki (SWOP)',
                'ordering': ['id_order'],
            },
        ),
        migrations.CreateModel(
            name='TypeUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_short', models.CharField(max_length=30, verbose_name='Skrócona nazwa')),
                ('type_full', models.CharField(max_length=100, verbose_name='Pełna nazwa')),
                ('id_order', models.IntegerField(null=True, unique=True, verbose_name='Kolejność')),
            ],
            options={
                'verbose_name': 'Rodzaj obiektu',
                'verbose_name_plural': '02 - Rodzaje obiektów',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50, verbose_name='Adres')),
                ('zip_code', models.CharField(max_length=6, verbose_name='Kod pocztowy')),
                ('city', models.CharField(max_length=40, verbose_name='Miasto')),
                ('unit_full_name', models.CharField(blank=True, max_length=200, verbose_name='Obiekt')),
                ('object_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nazwa obiektu')),
                ('manager', models.CharField(default='Policja', max_length=150, verbose_name='Administrator')),
                ('information', models.TextField(blank=True, null=True, verbose_name='Informacje')),
                ('status', models.BooleanField(default=True, verbose_name='Aktualna')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('change', models.DateTimeField(auto_now=True, verbose_name='Zmiany')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('county_swop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit', to='units.county', verbose_name='Jednostka SWOP')),
                ('county_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit', to='main.countycard', verbose_name='Powiat')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit', to='units.typeunit', verbose_name='Rodzaj obiektu')),
            ],
            options={
                'verbose_name': 'Obiekt',
                'verbose_name_plural': '04 - Obiekty',
                'ordering': ['county_swop__swop_id', 'type', 'object_name', 'information'],
            },
        ),
    ]
