# Generated by Django 4.1.7 on 2023-03-26 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='county',
            options={'ordering': ['id_order'], 'verbose_name': 'Jednostka SWOP', 'verbose_name_plural': 'Jednostki SWOP'},
        ),
    ]
