# Generated by Django 4.1.7 on 2023-09-08 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='object_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nazwa obiektu'),
        ),
    ]
