# Generated by Django 4.1.7 on 2023-03-26 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0002_alter_county_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='county',
            name='swop_id',
            field=models.CharField(max_length=4, verbose_name='ID SWOP'),
        ),
    ]
