# Generated by Django 4.1.7 on 2023-09-10 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0002_unit_object_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='county',
            options={'ordering': ['id_order'], 'verbose_name': 'Jednostka SWOP', 'verbose_name_plural': '01 - Jednostki (SWOP)'},
        ),
        migrations.AlterModelOptions(
            name='typeunit',
            options={'ordering': ['id'], 'verbose_name': 'Rodzaj obiektu', 'verbose_name_plural': '02 - Rodzaje obiektów'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['county_swop__swop_id', 'type'], 'verbose_name': 'Obiekt', 'verbose_name_plural': '03 - Obiekty'},
        ),
    ]
