# Generated by Django 4.1.7 on 2023-09-10 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0003_alter_county_options_alter_typeunit_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Rodzaj kosztu')),
            ],
            options={
                'verbose_name': 'Rodzaj kosztów',
                'verbose_name_plural': '03 - Rodzaje kosztów',
            },
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['county_swop__swop_id', 'type'], 'verbose_name': 'Obiekt', 'verbose_name_plural': '04 - Obiekty'},
        ),
        migrations.AddField(
            model_name='unit',
            name='cost_type',
            field=models.ManyToManyField(related_name='unit', to='units.costtype', verbose_name='Rodzaj kosztów'),
        ),
    ]
