# Generated by Django 4.1.7 on 2023-03-26 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0003_alter_county_swop_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='county',
            name='name',
            field=models.CharField(max_length=15, unique=True, verbose_name='Jednostka'),
        ),
    ]
