# Generated by Django 4.1.7 on 2023-03-26 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('units', '0004_alter_county_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_short', models.CharField(max_length=30, verbose_name='Skrócona nazwa')),
                ('type_full', models.CharField(max_length=100, verbose_name='Pełna nazwa')),
            ],
            options={
                'verbose_name': 'Rodzaj obiektu',
                'verbose_name_plural': 'Rodzaje obiektów',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50, verbose_name='Adres')),
                ('zip_code', models.CharField(max_length=6, verbose_name='Kod pocztowy')),
                ('city', models.CharField(max_length=40, verbose_name='Miasto')),
                ('unit_full_name', models.CharField(blank=True, max_length=200, verbose_name='Obiekt')),
                ('manager', models.CharField(default='Policja', max_length=150, verbose_name='Administrator')),
                ('information', models.TextField(blank=True, verbose_name='Informacje')),
                ('status', models.BooleanField(default=True, verbose_name='Aktualna')),
                ('slug', models.SlugField(unique=True)),
                ('change', models.DateTimeField(auto_now=True, verbose_name='Zmiany')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit', to='units.county', verbose_name='Powiat')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit', to='units.typeunit', verbose_name='Rodzaj obiektu')),
            ],
            options={
                'verbose_name': 'Jednostka',
                'verbose_name_plural': 'Jednostki',
                'ordering': ['county__name', 'type'],
            },
        ),
    ]
