# Generated by Django 4.1.7 on 2023-09-10 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0004_costtype_alter_unit_options_unit_cost_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='cost_type',
        ),
        migrations.DeleteModel(
            name='CostType',
        ),
    ]
