# Generated by Django 4.1.7 on 2023-03-26 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0005_typeunit_unit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['county__name', 'type'], 'verbose_name': 'Obiekt', 'verbose_name_plural': 'Obiekty'},
        ),
        migrations.AlterField(
            model_name='unit',
            name='county',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit', to='units.county', verbose_name='Jednostka'),
        ),
    ]
