# Generated by Django 4.2.1 on 2023-12-04 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0005_remove_unit_cost_type_delete_costtype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['county_swop__swop_id', 'type', 'object_name', 'information'], 'verbose_name': 'Obiekt', 'verbose_name_plural': '04 - Obiekty'},
        ),
    ]
