# Generated by Django 4.1.7 on 2023-03-26 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_countycard_unit_county'),
        ('units', '0006_alter_unit_options_alter_unit_county'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['county_swop__swop_id', 'type'], 'verbose_name': 'Obiekt', 'verbose_name_plural': 'Obiekty'},
        ),
        migrations.RenameField(
            model_name='unit',
            old_name='county',
            new_name='county_swop',
        ),
        migrations.AddField(
            model_name='unit',
            name='county_unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='unit', to='main.countycard', verbose_name='Powiat'),
            preserve_default=False,
        ),
    ]
