# Generated by Django 4.1.7 on 2023-03-26 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0007_alter_unit_options_rename_county_unit_county_swop_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='county_swop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit', to='units.county', verbose_name='Jednostka SWOP'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='information',
            field=models.TextField(blank=True, null=True, verbose_name='Informacje'),
        ),
    ]
