# Generated by Django 4.2.1 on 2023-07-27 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0008_alter_unit_county_swop_alter_unit_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeunit',
            name='id_order',
            field=models.IntegerField(null=True, unique=True, verbose_name='Kolejność'),
        ),
    ]
