# Generated by Django 4.1.7 on 2023-03-25 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountyCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True, verbose_name='Jednostka powiatowa')),
                ('id_order', models.IntegerField(null=True, unique=True, verbose_name='Kolejność')),
            ],
            options={
                'verbose_name': 'Jednostka powiatowa',
                'verbose_name_plural': 'Jednostki powiatowe',
                'ordering': ['id_order'],
            },
        ),
    ]
