# Generated by Django 4.2.1 on 2023-09-08 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='helpinfo',
            options={'verbose_name': 'Informacja', 'verbose_name_plural': 'Informacje'},
        ),
    ]
