# Generated by Django 4.1.7 on 2023-03-26 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='countycard',
            name='slug',
            field=models.SlugField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
