# Generated by Django 4.1.7 on 2023-09-10 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='countycard',
            options={'ordering': ['id_order'], 'verbose_name': 'Jednostka powiatowa', 'verbose_name_plural': '01 - Nazwy kart'},
        ),
        migrations.AlterModelOptions(
            name='helpinfo',
            options={'verbose_name': 'Informacja', 'verbose_name_plural': '02 - Informacje'},
        ),
    ]
