# Generated by Django 4.2.1 on 2023-11-13 06:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_countycard_options_alter_helpinfo_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helpinfo',
            name='information',
        ),
        migrations.AddField(
            model_name='helpinfo',
            name='info1',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Informacja_1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='helpinfo',
            name='info2',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Informacja_2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='helpinfo',
            name='info3',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Informacja_3'),
            preserve_default=False,
        ),
    ]
