# Generated by Django 4.1.7 on 2023-03-26 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0004_alter_county_name'),
        ('main', '0002_countycard_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='countycard',
            name='unit_county',
            field=models.ManyToManyField(related_name='county_card', to='units.county', verbose_name='Jednostki SWOP'),
        ),
    ]
