# Generated by Django 4.1.7 on 2023-03-26 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_countycard_unit_county'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information', models.TextField(verbose_name='Informacja')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Data dodania')),
                ('change', models.DateTimeField(auto_now=True, verbose_name='Zmiany')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='help_view', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Pomoc',
                'verbose_name_plural': 'Treść - Pomoc',
            },
        ),
    ]
