# Generated by Django 4.2.1 on 2023-11-26 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_helpinfo_information_helpinfo_info1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpinfo',
            name='info1',
            field=models.TextField(blank=True, null=True, verbose_name='Informacja_1'),
        ),
        migrations.AlterField(
            model_name='helpinfo',
            name='info2',
            field=models.TextField(blank=True, null=True, verbose_name='Informacja_2'),
        ),
        migrations.AlterField(
            model_name='helpinfo',
            name='info3',
            field=models.TextField(blank=True, null=True, verbose_name='Informacja_3'),
        ),
    ]
