# Generated by Django 4.2.1 on 2023-11-29 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_helpinfo_info1_alter_helpinfo_info2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helpinfo',
            name='info1',
        ),
        migrations.RemoveField(
            model_name='helpinfo',
            name='info2',
        ),
        migrations.RemoveField(
            model_name='helpinfo',
            name='info3',
        ),
        migrations.AddField(
            model_name='helpinfo',
            name='authorEmail',
            field=models.EmailField(default=1, max_length=254, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='helpinfo',
            name='authorPhone',
            field=models.CharField(default=1, max_length=9, verbose_name='Telefon'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='helpinfo',
            name='info',
            field=models.TextField(blank=True, null=True, verbose_name='Informacja'),
        ),
    ]
