# Generated by Django 4.1.7 on 2023-03-26 18:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_helpview'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HelpView',
            new_name='HelpInfo',
        ),
    ]
