# Generated by Django 4.1.7 on 2023-03-26 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_helpview_helpinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countycard',
            name='unit_county',
        ),
    ]
