# Generated by Django 4.1.7 on 2023-09-07 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_countycard_unit_county'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countycard',
            name='slug',
            field=models.SlugField(max_length=20, null=True),
        ),
    ]
