# Generated by Django 4.1.7 on 2023-09-07 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_countycard_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countycard',
            name='slug',
            field=models.SlugField(blank=True, max_length=20, null=True),
        ),
    ]
