# Generated by Django 4.2.1 on 2023-07-27 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_countycard_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countycard',
            name='slug',
            field=models.SlugField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
